language: node_js
node_js:
  - "16.20.1"

cache:
  directories:
    - node_modules

addons:
  sonarcloud:
    organization: "vlavrynovych"

install:
  - npm install

script:
  - mkdir backups
  - npm run test:report
  - npm run test:coverage:coveralls

  - echo "sonar.projectKey=vlavrynovych_msr-firebase" > sonar-project.properties
  - echo "sonar.organization=vlavrynovych" >> sonar-project.properties
  - echo "sonar.projectVersion=develop" >> sonar-project.properties
  - echo "sonar.projectName=MSR" >> sonar-project.properties
  - echo "sonar.javascript.lcov.reportPaths=reports/coverage/lcov.info" >> sonar-project.properties
  - echo "sonar.sources=src" >> sonar-project.properties
  - echo "sonar.tests=test" >> sonar-project.properties
  - echo "sonar.exclusions=test" >> sonar-project.properties
  - sonar-scanner