language: node_js
node_js:
  - "16.20.1"

cache:
  directories:
    - node_modules

addons:
  sonarcloud:
    organization: "vlavrynovych"

install:
  - npm install

script:
  - mkdir backups
  - npm run test:report
  - npm run test:coverage:coveralls
  - sonar-scanner