language: node_js
node_js:
  - "16.20.1"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - mkdir backups
  - mkdir key
  - echo $PRIVATE_KEY > $PWD/key/private_key.json
  - export GOOGLE_APPLICATION_CREDENTIALS="$PWD/key/private_key.json"
  - echo $GOOGLE_APPLICATION_CREDENTIALS
  - npm run test:report
  - npm run test:coverage:coveralls