language: node_js
node_js:
  - "16.20.1"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - source scripts/ci.sh
  - npm run test:report
  - npm run test:coverage:coveralls